[package]
name = "shadowbid"
version = "0.1.0"
description = "Privacy-preserving blind auction system on Solana with Arcium MPC"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]
name = "shadowbid"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "arcium-anchor/idl-build"]

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"
arcium-anchor = "0.9.7"
arcium-client = { version = "0.9.7", default-features = false }
arcium-macros = "0.9.7"
sha2 = "0.10"


[dev-dependencies]
